from flask_wtf import Form
from wtforms import StringField,SubmitField
from wtforms.validators import DataRequired


class predictionForm(Form):
	id = StringField('ID')
	credit_score = StringField('Credit Score', validators=[DataRequired(message ="Please enter credit score")])	
	first_payment_date = StringField('First Payment Date', validators=[DataRequired(message ="Please enter a First Payment Date")])
	fthb_flag = StringField('First Time house Buyer flag', validators=[DataRequired(message ="Please enter a fthb flag")])
	matr_date = StringField('Maturity Date', validators=[DataRequired(message ="Please enter Maturity Date")])
	msa = StringField('METROPOLITAN STATISTICAL AREA (MSA)', validators=[DataRequired(message ="Please enter MSA")])
	mortage_insurance_pct = StringField('Mortgage insurance percentage', validators=[DataRequired(message ="Please enter a MI")])
	no_of_units = StringField('No. of units', validators=[DataRequired(message ="Please enter number of units")])
	occupancy_status = StringField('Occupancy status', validators=[DataRequired(message ="Please enter Occupancy status")])
	cltv = StringField('ORIGINAL COMBINED LOAN-TO-VALUE', validators=[DataRequired(message ="Please enter cltv")])
	dti_ratio = StringField('ORIGINAL DEBT-TO-INCOME (DTI) RATIO', validators=[DataRequired(message ="Please enter DTI ratio")])
	original_upb = StringField('UPB', validators=[DataRequired(message ="Please enter UPB")])
	submit = SubmitField("Get interest rate")
    
class classificationForm(Form):
    id = StringField('ID')
    month = StringField('Month', validators=[DataRequired(message = "Please enter Month")])
    current_actual_upb= StringField('Current Actual UPB', validators=[DataRequired(message ="Please enter Current Actual UPB")])
    delq_status = StringField('Deliquent Status', validators=[DataRequired(message ="Please enter Deliquent Status")])
    loan_age = StringField('Loan Age', validators=[DataRequired(message ="Please enter Loan Age")])
    rem_months = StringField('Remaining Months', validators=[DataRequired(message ="Please enter Remaining Months")])
    zero_balance_code = StringField('zero_balance_code', validators=[DataRequired(message ="Please enter Zero Balance Code")])
    zero_bal_date = StringField('zero_bal_date', validators=[DataRequired(message ="Please enter Zero Balance Effective Date")])
    current_int_rate = StringField('current_int_rate', validators=[DataRequired(message ="Please enter Current Interest Rate")])
    current_def_upb = StringField('current_def_upb', validators=[DataRequired(message ="Please enter Current Deferred UPB")])
    ddlpi = StringField('ddlpi', validators=[DataRequired(message ="Please enter Due Date of Last Paid Installment")])
    mi_recoveries = StringField('mi_recoveries', validators=[DataRequired(message ="Please enter MI Recoveries")])
    net_sales_proceeds = StringField('net_sales_proceeds', validators=[DataRequired(message ="Please enter Net Sales Proceeds")])
    non_mi_recoveries = StringField('non_mi_recoveries', validators=[DataRequired(message ="Please enter Non MI Recoveries")])
    expenses = StringField('expenses', validators=[DataRequired(message ="Please enter expenses")])
    legal_costs = StringField('legal_costs', validators=[DataRequired(message ="Please enter legal_costs")])
    maint_pres_costs = StringField('maint_pres_costs', validators=[DataRequired(message ="Please enter Maintenance and Preservation costs ")])
    taxes_ins = StringField('taxes_ins', validators=[DataRequired(message ="Please enter Taxes and Insurance")])
    misc_expenses = StringField('misc_expenses', validators=[DataRequired(message ="Please enter Miscellaneous Expenses")])
    actual_loss_calc = StringField('actual_loss_calc', validators=[DataRequired(message ="Please enter Actual Loss Calculation")])
    modification_cost = StringField('modification_cost', validators=[DataRequired(message ="Please enter Modification Cost")])
    repurchase_flag_0 = StringField('repurchase_flag_0', validators=[DataRequired(message ="Please enter Repurchase Flag 0")])
    repurchase_flag_N = StringField('repurchase_flag_N', validators=[DataRequired(message ="Please enter Repurchase Flag N")])
    repurchase_flag_Y = StringField('repurchase_flag_Y', validators=[DataRequired(message ="Please enter Repurchase Flag Y")])
    modification_flag_0 = StringField('modification_flag_0', validators=[DataRequired(message ="Please enter Modification Flag 0")])
    modification_flag_Y = StringField('modification_flag_Y', validators=[DataRequired(message ="Please enter Modification Flag Y")])
    Deliquent = StringField('Deliquent', validators=[DataRequired(message ="Please enter Deliquent")])
    submit = SubmitField("Get Results")